name: wg_gesucht_scraper
runtime: python3_10
description: Scrapes WG-Gesucht website listings based on specific filters such as city, rent range, room size, etc., requiring login credentials and CSRF token handling.

interface:
  inputs:
    type: object
    properties:
      WG_USERNAME:
        type: env
        description: WG-Gesucht account username for login.
      WG_PASSWORD:
        type: env
        description: WG-Gesucht account password for login.
      filter:
        type: object
        description: Filters for listing search on WG-Gesucht.
        properties:
          city_id:
            type: integer
            description: ID of the city to search within.
          rent_max:
            type: integer
            description: Maximum rent allowed for listings.
          room_size_min:
            type: integer
            description: Minimum room size in square meters.
          rm_min:
            type: integer
            description: Minimum number of rooms required.
          district_codes:
            type: string
            description: Comma-separated list of district codes to filter by.
          only_furnished:
            type: boolean
            description: Whether to include only furnished listings.
          max_online_time:
            type: integer
            description: Maximum online time in hours for listings.
          balcony:
            type: boolean
            description: Whether to include listings with a balcony.
          move_in_earliest:
            type: string
            format: date
            description: Earliest move-in date for the listings.
          min_stay_days:
            type: integer
            description: Minimum required stay in days.
        required: ["city_id"]
  outputs:
    type: object
    properties:
      listings:
        type: array
        items:
          type: object
          properties:
            title:
              type: string
              description: Title of the listing.
            link:
              type: string
              description: URL link to the listing.
            rent:
              type: integer
              description: Monthly rent cost for the listing.
            room_size:
              type: integer
              description: Room size in square meters.
            availability_start:
              type: string
              format: date
              description: Start date of availability.
            availability_end:
              type: string
              format: date
              description: End date of availability.
            stay_days:
              type: integer
              description: Duration of stay in days.
            room_count:
              type: integer
              description: Number of rooms available.
            city_area:
              type: string
              description: Area of the city where the listing is located.
            street:
              type: string
              description: Street of the listing location.
            lister_name:
              type: string
              description: Name of the person who posted the listing.
            description:
              type: string
              description: Text description of the listing.