name: "WGSearch"
runtime: python3_10
description: "Search for WG-gesucht listings in a specified city with customizable filters."
interface:
  inputs:
    properties:
      WG_USERNAME:
        type: "env"
        description: "Environment variable for the WG-Gesucht username."
      WG_PASSWORD:
        type: "env"
        description: "Environment variable for the WG-Gesucht password."
      filter:
        type: object
        description: "Filter options for the search query"
        properties:
          city:
            type: string
            description: "The city for the listing search, e.g., 'Berlin' or 'Munich'. Defaults to 'Berlin' if not provided."
          rent_max:
            type: integer
            description: "Maximum rent price in EUR."
          room_size_min:
            type: integer
            description: "Minimum room size in square meters."
          only_furnished:
            type: boolean
            description: "If true, only furnished rooms are listed."
          max_online_time:
            type: integer
            description: "Maximum number of hours since the listing was posted."
          balcony:
            type: boolean
            description: "If true, filters listings that have a balcony."
          move_in_earliest:
            type: string
            description: "Earliest move-in date in YYYY-MM-DD format."
          move_in_latest:
            type: string
            description: "Latest move-in date in YYYY-MM-DD format."
          min_stay_days:
            type: integer
            description: "Minimum duration of stay in days."
        required: []
  outputs:
    properties:
      listings:
        type: array
        description: "List of filtered listings based on search criteria."
        items:
          type: object
          properties:
            title:
              type: string
              description: "Title of the listing."
            link:
              type: string
              description: "Link to the listing on WG-gesucht."
            rent:
              type: integer
              description: "Monthly rent price in EUR."
            room_size:
              type: integer
              description: "Room size in square meters."
            availability_start:
              type: string
              description: "Start date of availability, in DD.MM.YYYY format."
            availability_end:
              type: string
              description: "End date of availability, in DD.MM.YYYY format."
            stay_days:
              type: integer
              description: "Number of days the listing is available."
            room_count:
              type: integer
              description: "Number of rooms in the listing."
            city_area:
              type: string
              description: "City area or district."
            street:
              type: string
              description: "Street address, if available."
            lister_name:
              type: string
              description: "Name of the person who listed the ad."
            description:
              type: string
              description: "Detailed description of the listing."
        required: ["title", "link", "rent", "room_size"]
