apiVersion: "0.0.1"
title: Generate edurata configs from openapi schema
interface:
  inputs:
    function-name:
      required: true
    open-api-schema-url:
      required: true
    commit-to-repo:
      default: true
    commit-to-revision:
      default: HEAD
steps:
  get-api-schema:
    source: 
      repoUrl: https://github.com/Edurata/edurata-functions.git
      path: pull-file
    inputs:
      repoUrl: $.inputs.open-api-schema-url
  generate-files-from-schema:
    source: 
      repoUrl: https://github.com/Edurata/edurata-functions.git
      path: generate-files-from-oas
    inputs: 
      schema: $.get-api-schema.content
  commit-to-git:
    if: $.inputs.commit-to-repo
    source: 
      repoUrl: https://github.com/Edurata/edurata-functions.git
      path: handle-git
    inputs:
      action: push
      repoUrl: $.inputs.commit-to-revision
      revision: $.inputs.commit-to-revision
      tokenName: $.secrets.gitlab-access-token
      tokenSecret: $.secrets.gitlab-token-user


