name: freelancermap_job_filter
runtime: python3_10
description: A function that logs into Freelancermap, extracts job descriptions, and filters them based on keywords and elapsed days since posting..
interface:
  inputs:
    properties:
      FREELANCERMAP_USERNAME:
        type: env
        description: The username for logging into Freelancermap.
      FREELANCERMAP_PASSWORD:
        type: env
        description: The password for logging into Freelancermap.
      positive_keywords:
        type: string
        description: List of comma-separated positive keywords to filter jobs.
      negative_keywords:
        type: string
        description: List of comma-separated negative keywords to exclude jobs.
      max_elapsed_days:
        type: integer
        description: Maximum number of days since the job was posted for it to be included in the results.
    required:
      [
        FREELANCERMAP_USERNAME,
        FREELANCERMAP_PASSWORD,
        positive_keywords,
        max_elapsed_days,
      ]
  outputs:
    properties:
      matching_jobs:
        type: array
        description: List of jobs that match the given criteria.
        items:
          type: object
          properties:
            title:
              type: string
              description: The job title.
            content:
              type: string
              description: The full content of the job message.
            date:
              type: string
              description: The posting date of the job in ISO format.
