name: list_outlook_conversations_bulk
runtime: nodejs20
description: |
  Bulk, stateless Outlook conversation classifier for a sender domain, using a rolling time window.

  The function pulls Inbox messages (metadata only) within a time window and reduces them to the latest
  inbound message per conversationId. It then pulls Sent Items within the same window (metadata only)
  to determine which conversations are already answered (latestSentDateTime > latestInboundReceivedDateTime).
  It also checks Drafts for the relevant conversationIds (chunked OR filter) and marks conversations as needing
  attention if the conversation is not answered and either:
    - no draft exists in the conversation, or
    - the newest drafts lastModifiedDateTime is older than the latest inbound receivedDateTime (outdated draft).
  Intended to run frequently (e.g. every 10 minutes). Does not read message bodies. Does not write labels/categories.
interface:
  inputs:
    properties:
      OUTLOOK_API_KEY:
        type: env
        description: OAuth 2.0 Bearer token for Microsoft Graph.
      senderDomain:
        type: string
        description: Sender domain to filter inbound messages by (e.g. "company.com"). Uses contains(from/emailAddress/address, senderDomain).
      windowHours:
        type: number
        description: Rolling time window in hours to consider inbound and sent messages (default 72).
        default: 72
      pageSize:
        type: number
        description: Page size for Graph list calls ($top). Graph typically maxes at 100. Default 100.
        default: 100
      maxInboxPages:
        type: number
        description: Max number of paginated pages to fetch from Inbox (default 3). Bounds runtime and API usage.
        default: 3
      maxSentPages:
        type: number
        description: Max number of paginated pages to fetch from Sent Items (default 3). Bounds runtime and API usage.
        default: 3
      draftChunkSize:
        type: number
        description: Number of conversationIds per Drafts query chunk (OR filter). Default 15.
        default: 15
      onlyEdurataDrafts:
        type: boolean
        description: Optional. If true, only consider drafts that have the Outlook category "EdurataDraft" when checking for existing/outdated drafts. Default false.
        default: false
      maxUnanswered:
        type: number
        description: Max number of unanswered conversations to return. Default 10; use 0 for no limit.
        default: 10
    required:
      - senderDomain
  outputs:
    properties:
      unansweredConversationIds:
        type: array
        description: >
          List of conversationIds that need attention (capped by maxUnanswered). A conversation is included if its
          latest inbound message (within the window) is not answered and the conversation has no draft or only an outdated draft.
        items:
          type: string
      answeredConversationIds:
        type: array
        description: >
          List of conversationIds whose latest inbound message is already answered.
        items:
          type: string
      countUnanswered:
        type: number
        description: Number of unansweredConversationIds returned.
      countAnswered:
        type: number
        description: Number of answeredConversationIds returned.
      sinceUsed:
        type: string
        description: ISO 8601 datetime used as the lower bound (now - windowHours).
    required:
      - unansweredConversationIds
      - answeredConversationIds
      - countUnanswered
      - countAnswered
      - sinceUsed
